site_url: https://sage-griffin-303b4f.netlify.app
backend:
  name: git-gateway
  branch: master

media_folder: assets/images
public_folder: assets/images

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Info"
        file: "_data/settings.json"
        fields:
          - { label: "Hours", name: "hours", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
